export const governorates: Record<string, string> = {
  'cairo': 'القاهرة',
  'alexandria': 'الإسكندرية',
  'giza': 'الجيزة',
  'asyut': 'أسيوط',
  'port-said': 'بورسعيد',
  'suez': 'السويس',
  ' Ismailia': 'الإسماعيلية',
  'faiyum': 'الفيوم',
  'minya': 'المنيا',
  'qena': 'قنا',
  'sohag': 'سوهاج',
  'bani-suef': 'بني سويف',
  'tanta': 'طنطا',
  'zagazig': 'الزقازيق',
  'ismailia': 'الإسماعيلية',
  'damanhur': 'دمنهور',
  'fayoum-city': 'مدينة الفيوم',
  'mallawi': 'ملاوي',
  'idsui': 'ال إدريسي',
  'akhour': 'العاشر من رمضان',
  'shibin-el-kom': 'شبين الكوم',
  'banha': 'بنها',
  'dikirnis': 'دكرنس',
  'mit-ghamr': 'ميت غمر',
  'sharm-el-sheikh': 'شرم الشيخ',
  'hurghada': 'الغردقة',
  'luxor': 'الأقصر',
  'aswan': 'أسوان',
  'dakhla': 'الوادي الجديد',
  'el-arish': 'العريش',
  'kafr-el-sheikh': 'كفر الشيخ',
  'menoufia': 'المنوفية',
  'behira': 'البحيرة',
  'gharbia': 'الغربية',
  'monufia': 'المنوفية',
  'qalyubia': 'القليوبية',
  'new-valley': 'الوادي الجديد',
  'matrouh': 'مرسى مطروح',
  'red-sea': 'البحر الأحمر',
  'south-sinai': 'جنوب سيناء',
  'north-sinai': 'شمال سيناء',
  'damietta': 'دمياط',
}

export const governoratesList = [
  { value: 'cairo', label: 'القاهرة' },
  { value: 'alexandria', label: 'الإسكندرية' },
  { value: 'giza', label: 'الجيزة' },
  { value: 'asyut', label: 'أسيوط' },
  { value: 'port-said', label: 'بورسعيد' },
  { value: 'suez', label: 'السويس' },
  { value: 'ismailia', label: 'الإسماعيلية' },
  { value: 'faiyum', label: 'الفيوم' },
  { value: 'minya', label: 'المنيا' },
  { value: 'qena', label: 'قنا' },
  { value: 'sohag', label: 'سوهاج' },
  { value: 'bani-suef', label: 'بني سويف' },
  { value: 'tanta', label: 'طنطا' },
  { value: 'zagazig', label: 'الزقازيق' },
  { value: 'damanhur', label: 'دمنهور' },
  { value: 'shibin-el-kom', label: 'شبين الكوم' },
  { value: 'banha', label: 'بنها' },
  { value: 'mit-ghamr', label: 'ميت غمر' },
  { value: 'sharm-el-sheikh', label: 'شرم الشيخ' },
  { value: 'hurghada', label: 'الغردقة' },
  { value: 'luxor', label: 'الأقصر' },
  { value: 'aswan', label: 'أسوان' },
  { value: 'el-arish', label: 'العريش' },
  { value: 'kafr-el-sheikh', label: 'كفر الشيخ' },
  { value: 'menoufia', label: 'المنوفية' },
  { value: 'behira', label: 'البحيرة' },
  { value: 'gharbia', label: 'الغربية' },
  { value: 'qalyubia', label: 'القليوبية' },
  { value: 'new-valley', label: 'الوادي الجديد' },
  { value: 'matrouh', label: 'مرسى مطروح' },
  { value: 'red-sea', label: 'البحر الأحمر' },
  { value: 'south-sinai', label: 'جنوب سيناء' },
  { value: 'north-sinai', label: 'شمال سيناء' },
  { value: 'damietta', label: 'دمياط' },
]

export const governoratesLabel = (value: string): string => {
  return governoratesList.find((g) => g.value === value)?.label || value
}
