'use client'

import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export type Language = 'ar' | 'en'

interface LangState {
  lang: Language
  setLang: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<string, Record<Language, string>> = {
  // Navigation
  'nav.dashboard': { ar: 'لوحة التحكم', en: 'Dashboard' },
  'nav.seats': { ar: 'خريطة المقاعد', en: 'Seats Map' },
  'nav.buses': { ar: 'الباصات', en: 'Buses' },
  'nav.trips': { ar: 'الرحلات', en: 'Trips' },
  'nav.bookings': { ar: 'الحجوزات', en: 'Bookings' },
  'nav.customers': { ar: 'العملاء', en: 'Customers' },
  'nav.users': { ar: 'إدارة المستخدمين', en: 'User Management' },
  'nav.verify': { ar: 'التحقق من الصعود', en: 'Verify Boarding' },
  'nav.reports': { ar: 'التقارير', en: 'Reports' },
  'nav.stations': { ar: 'المحطات', en: 'Stations' },
  'nav.faq': { ar: 'الأسئلة الشائعة', en: 'FAQ' },
  'nav.signOut': { ar: 'تسجيل الخروج', en: 'Sign Out' },
  'nav.admin': { ar: 'الإدارة', en: 'Admin' },

  // Dashboard
  'dashboard.welcome': { ar: 'مرحباً', en: 'Welcome back' },
  'dashboard.totalBookings': { ar: 'إجمالي الحجوزات', en: 'Total Bookings' },
  'dashboard.totalRevenue': { ar: 'إجمالي الإيرادات', en: 'Total Revenue' },
  'dashboard.activeTrips': { ar: 'الرحلات النشطة', en: 'Active Trips' },
  'dashboard.todayRevenue': { ar: 'إيرادات اليوم', en: "Today's Revenue" },
  'dashboard.revenueTrend': { ar: 'اتجاه الإيرادات', en: 'Revenue Trend' },
  'dashboard.last30days': { ar: 'آخر 30 يوم', en: 'Last 30 days' },
  'dashboard.recentBookings': { ar: 'الحجوزات الأخيرة', en: 'Recent Bookings' },
  'dashboard.viewAll': { ar: 'عرض الكل', en: 'View all' },
  'dashboard.manageBuses': { ar: 'إدارة الباصات', en: 'Manage Buses' },
  'dashboard.manageTrips': { ar: 'إدارة الرحلات', en: 'Manage Trips' },
  'dashboard.viewTrips': { ar: 'عرض الرحلات', en: 'View Trips' },
  'dashboard.addBuses': { ar: 'أضف باصات وصمم المقاعد', en: 'Add buses and design seat layouts' },
  'dashboard.createTrips': { ar: 'أنشئ وجدول الرحلات', en: 'Create and schedule trips' },
  'dashboard.seeTrips': { ar: 'شوف كل الرحلات', en: 'See all available trips' },
  'dashboard.reviewCompanies': { ar: 'راجع وفعّل الشركات', en: 'Review & activate companies' },

  // Buses
  'buses.title': { ar: 'الباصات', en: 'Buses' },
  'buses.manage': { ar: 'إدارة الأسطول', en: 'Manage your fleet' },
  'buses.addBus': { ar: 'إضافة باص', en: 'Add Bus' },
  'buses.noBuses': { ar: 'لا توجد باصات', en: 'No buses yet' },
  'buses.addFirst': { ar: 'أضف باصك الأول', en: 'Add your first bus' },
  'buses.seatsConfig': { ar: 'مقاعد مُهيأة', en: 'seats configured' },
  'buses.editLayout': { ar: 'تعديل التصميم', en: 'Edit Layout' },
  'buses.designLayout': { ar: 'تصميم المقاعد', en: 'Design Layout' },
  'buses.addNew': { ar: 'إضافة باص جديد', en: 'Add New Bus' },
  'buses.busName': { ar: 'اسم الباص', en: 'Bus Name' },
  'buses.busType': { ar: 'نوع الباص', en: 'Bus Type' },
  'buses.companyId': { ar: 'رقم الشركة', en: 'Company ID' },
  'buses.cancel': { ar: 'إلغاء', en: 'Cancel' },
  'buses.create': { ar: 'إنشاء', en: 'Create' },

  // Bus types
  'busType.mini': { ar: 'ميني باص', en: 'Mini Bus' },
  'busType.coach': { ar: 'كوتش', en: 'Coach Bus' },
  'busType.vip': { ar: 'VIP', en: 'VIP Bus' },
  'busType.double': { ar: 'دبل ديكار', en: 'Double Decker' },

  // Layout
  'layout.title': { ar: 'تصميم المقاعد', en: 'Seat Layout' },
  'layout.design': { ar: 'صمم مقاعد الباص', en: 'Design your bus seats' },
  'layout.save': { ar: 'حفظ التصميم', en: 'Save Layout' },
  'layout.info': { ar: 'معلومات التصميم', en: 'Layout Info' },
  'layout.rows': { ar: 'الصفوف', en: 'Rows' },
  'layout.cols': { ar: 'الأعمدة', en: 'Columns' },
  'layout.totalSeats': { ar: 'إجمالي المقاعد', en: 'Total Seats' },
  'layout.legend': { ar: 'أنواع المقاعد', en: 'Seat Types' },
  'layout.editSeat': { ar: 'تعديل المقعد', en: 'Edit Seat' },
  'layout.normal': { ar: 'عادي', en: 'Normal' },
  'layout.vip': { ar: 'VIP', en: 'VIP' },
  'layout.disabled': { ar: 'لذوي الإحتياجات', en: 'Disabled' },
  'layout.extraPrice': { ar: 'سعر إضافي (ج.م)', en: 'Extra Price (EGP)' },
  'layout.front': { ar: 'الأمام', en: 'FRONT' },

  // Trips
  'trips.title': { ar: 'الرحلات', en: 'Trips' },
  'trips.manage': { ar: 'إدارة المسارات والجدول', en: 'Manage your routes and schedules' },
  'trips.addTrip': { ar: 'إضافة رحلة', en: 'Add Trip' },
  'trips.bulkCreate': { ar: 'إنشاء متعدد', en: 'Bulk Create' },
  'trips.noTrips': { ar: 'لا توجد رحلات', en: 'No trips yet' },
  'trips.createFirst': { ar: 'أنشئ رحلتك الأولى', en: 'Create your first trip' },
  'trips.origin': { ar: 'النقطة الأصلية', en: 'Origin' },
  'trips.destination': { ar: 'الوجهة', en: 'Destination' },
  'trips.departure': { ar: 'المغادرة', en: 'Departure' },
  'trips.arrival': { ar: 'الوصول', en: 'Arrival' },
  'trips.price': { ar: 'السعر', en: 'Price' },
  'trips.bus': { ar: 'الباص', en: 'Bus' },
  'trips.status': { ar: 'الحالة', en: 'Status' },
  'trips.bookings': { ar: 'حجز', en: 'bookings' },

  // Trip Status
  'status.scheduled': { ar: 'مجدولة', en: 'Scheduled' },
  'status.inProgress': { ar: 'جارية', en: 'In Progress' },
  'status.completed': { ar: 'مكتملة', en: 'Completed' },
  'status.cancelled': { ar: 'ملغاة', en: 'Cancelled' },

  // Bulk Create
  'bulk.title': { ar: 'إنشاء رحلات متعددة', en: 'Bulk Create Trips' },
  'bulk.subtitle': { ar: 'أنشئ رحلات كثيرة دفعة واحدة', en: 'Create multiple trips at once' },
  'bulk.numTrips': { ar: 'عدد الرحلات', en: 'Number of Trips' },
  'bulk.interval': { ar: 'التكرار', en: 'Interval' },
  'bulk.daily': { ar: 'يومي', en: 'Daily' },
  'bulk.weekly': { ar: 'أسبوعي', en: 'Weekly' },
  'bulk.weekdays': { ar: 'أيام العمل', en: 'Weekdays (Mon-Fri)' },
  'bulk.preview': { ar: 'معاينة', en: 'Preview' },
  'bulk.firstTrips': { ar: 'أول 3 رحلات', en: 'first 3 trips' },
  'bulk.andMore': { ar: 'و المزيد', en: 'more' },

  // Edit Trip
  'editTrip.title': { ar: 'تعديل الرحلة', en: 'Edit Trip' },
  'editTrip.update': { ar: 'تحديث المسار والجدول', en: 'Update route and schedule' },
  'editTrip.save': { ar: 'حفظ التغييرات', en: 'Save Changes' },

  // Bookings
  'bookings.title': { ar: 'الحجوزات', en: 'Bookings' },
  'bookings.all': { ar: 'كل الحجوزات', en: 'All reservations' },
  'bookings.search': { ar: 'ابحث في الحجوزات...', en: 'Search bookings...' },
  'bookings.noBookings': { ar: 'لا توجد حجوزات', en: 'No bookings found' },
  'bookings.noBookingsDesc': { ar: 'الحجوزات هتظهر هنا لما العملاء يحجزوا مقاعد', en: 'Bookings will appear here when customers reserve seats' },
  'bookings.reference': { ar: 'المرجع', en: 'Reference' },
  'bookings.customer': { ar: 'العميل', en: 'Customer' },
  'bookings.route': { ar: 'المسار', en: 'Route' },
  'bookings.seat': { ar: 'المقعد', en: 'Seat' },

  // Search Trips (Customer)
  'search.title': { ar: 'ابحث عن رحلة', en: 'Find a Trip' },
  'search.desc': { ar: 'ابحث عن المسارات المتاحة واحجز مقعدك', en: 'Search for available routes and book your seat' },
  'search.from': { ar: 'من', en: 'From' },
  'search.to': { ar: 'إلى', en: 'To' },
  'search.date': { ar: 'التاريخ', en: 'Date' },
  'search.searchBtn': { ar: 'بحث', en: 'Search' },
  'search.noTrips': { ar: 'مفيش رحلات', en: 'No trips found' },
  'search.tryAgain': { ar: 'جرب تغيّر البحث أو شوف تاني وقت', en: 'Try adjusting your search or check back later' },
  'search.seatsLeft': { ar: 'مقاعد متبقية', en: 'seats left' },
  'search.fullyBooked': { ar: 'مكتملة', en: 'Fully booked' },
  'search.chooseSeat': { ar: 'اختار مقعد', en: 'Choose Seat' },
  'search.soldOut': { ar: 'مفيش مقاعد', en: 'Sold Out' },
  'search.perSeat': { ar: 'للمقعد', en: 'per seat' },

  // Seat Booking
  'seat.select': { ar: 'اختار مقعدك', en: 'Select Your Seat' },
  'seat.available': { ar: 'متاح', en: 'Available' },
  'seat.selected': { ar: 'مختار', en: 'Selected' },
  'seat.reserved': { ar: 'محجوز', en: 'Reserved' },
  'seat.vipSeat': { ar: 'VIP', en: 'VIP' },
  'seat.summary': { ar: 'ملخص الحجز', en: 'Booking Summary' },
  'seat.selectedSeats': { ar: 'المقاعد المختارة', en: 'Selected Seats' },
  'seat.clickSeat': { ar: 'اضغط على مقعد للاختيار', en: 'Click a seat to select' },
  'seat.total': { ar: 'الإجمالي', en: 'Total' },
  'seat.bookBtn': { ar: 'احجز', en: 'Book' },
  'seat.selectFirst': { ar: 'اختار مقعد عشان تكمل', en: 'Select a seat to continue' },
  'seat.cancel': { ar: 'إلغاء مجاني خلال ساعة', en: 'Free cancellation within 1 hour' },

  // Booking statuses
  'booking.pending': { ar: 'قيد الانتظار', en: 'Pending' },
  'booking.paid': { ar: 'مؤكد', en: 'Confirmed' },
  'booking.cancelled': { ar: 'ملغي', en: 'Cancelled' },
  'booking.boarded': { ar: 'صعد', en: 'Boarded' },

  // Booking Confirmed
  'confirmed.title': { ar: 'تم الحجز بنجاح!', en: 'Booking Confirmed!' },
  'confirmed.desc': { ar: 'تم حجز مقعدك بنجاح', en: 'Your seat has been reserved successfully' },
  'confirmed.totalPaid': { ar: 'إجمالي المدفوع', en: 'Total Paid' },
  'confirmed.bookAnother': { ar: 'احجز مقعد تاني', en: 'Book Another Seat' },

  // Landing
  'landing.title': { ar: 'احجز مقعدك', en: 'Book your seat' },
  'landing.subtitle': { ar: 'في ثواني', en: 'in seconds.' },
  'landing.desc': { ar: 'منصة حجز مقاعد باصات عصرية للرحلات. خرائط مقاعد جميلة، حجز فوري، وتحليلات قوية.', en: 'Modern realtime seat booking platform for transportation companies. Beautiful seat maps, instant reservations, and powerful analytics.' },
  'landing.start': { ar: 'ابدأ مجاناً', en: 'Start Free' },
  'landing.browse': { ar: 'تصفح الرحلات', en: 'Browse Trips' },
  'landing.realtime': { ar: 'حجز لحظي', en: 'Realtime seat booking' },
  'landing.features': { ar: 'كل اللي تحتاجه', en: 'Everything you need' },
  'landing.builtFor': { ar: 'صُممت لشركات النقل الحديثة', en: 'Built for modern transportation companies' },
  'landing.seatMap': { ar: 'خريطة مقاعد تفاعلية', en: 'Interactive Seat Map' },
  'landing.seatMapDesc': { ar: 'العملاء يختاروا المقاعد بصرياً مع توفر لحظي', en: 'Customers select seats visually with real-time availability' },
  'landing.instant': { ar: 'حجز فوري', en: 'Instant Booking' },
  'landing.instantDesc': { ar: 'احجز مقعد في ثواني مع تجربة اختيار سلسة', en: 'Book seats in seconds with animated selection experience' },
  'landing.analytics': { ar: 'تحليلات متقدمة', en: 'Analytics Dashboard' },
  'landing.analyticsDesc': { ar: 'تابع الإيرادات، نسبة الإشغال، واتجاهات الحجوزات', en: 'Track revenue, occupancy, and booking trends' },
  'landing.busMgmt': { ar: 'إدارة الباصات', en: 'Bus Management' },
  'landing.busMgmtDesc': { ar: 'أنشئ باصات وصمم تخطيط المقاعد', en: 'Create buses and design custom seat layouts' },
  'landing.howIt': { ar: 'إزاي يعمل', en: 'How it works' },
  'landing.threeSteps': { ar: 'ثلاث خطوات بسيطة لحجز أفضل', en: 'Three simple steps to better bookings' },
  'landing.createBuses': { ar: 'أنشئ باصات', en: 'Create Buses' },
  'landing.createBusesDesc': { ar: 'أضف أسطولك وصمم تخطيط المقاعد بالـ drag-and-drop', en: 'Add your fleet and design seat layouts with our drag-and-drop builder' },
  'landing.addTrips': { ar: 'أضف رحلات', en: 'Add Trips' },
  'landing.addTripsDesc': { ar: 'حدد المسارات والأوقات والأسعار لكل رحلة', en: 'Set routes, times, and pricing for each journey' },
  'landing.startBooking': { ar: 'ابدأ الحجز', en: 'Start Booking' },
  'landing.startBookingDesc': { ar: 'العملاء يختاروا المقاعد بصرياً ويحجزوا فوراً', en: 'Customers choose seats visually and book instantly' },
  'landing.pricing': { ar: 'أسعار بسيطة', en: 'Simple pricing' },
  'landing.pricingSub': { ar: 'ابدأ مجاناً وطور لما تحتاج أكتر', en: 'Start free, upgrade when you need more' },
  'landing.popular': { ar: 'الأكثر شعبية', en: 'Popular' },
  'landing.perMonth': { ar: '/شهر', en: '/mo' },
  'landing.getStarted': { ar: 'ابدأ الآن', en: 'Get Started' },
  'landing.loved': { ar: 'شركات بتحبه', en: 'Loved by companies' },
  'landing.lovedDesc': { ar: 'موثوق من شركات النقل في مصر', en: 'Trusted by transportation companies across Egypt' },
  'landing.cta': { ar: 'جاهز تحول حجز الباصات؟', en: 'Ready to transform your bus bookings?' },
  'landing.ctaDesc': { ar: 'انضم لمئات الشركات اللي بتستخدم CrushCar', en: 'Join hundreds of companies already using CrushCar' },
  'landing.ctaBtn': { ar: 'ابدأ مجاناً', en: 'Start for Free' },

  // Auth
  'auth.welcome': { ar: 'مرحباً بعودتك', en: 'Welcome back' },
  'auth.signInAccount': { ar: 'سجل دخولك', en: 'Sign in to your account' },
  'auth.email': { ar: 'البريد الإلكتروني', en: 'Email' },
  'auth.password': { ar: 'كلمة المرور', en: 'Password' },
  'auth.noAccount': { ar: 'مفيش حساب؟', en: "Don't have an account?" },
  'auth.createOne': { ar: 'أنشئ حساب', en: 'Create one' },
  'auth.createAccount': { ar: 'أنشئ حساب', en: 'Create account' },
  'auth.joinToday': { ar: 'انضم إلى سفرو اليوم', en: 'Join Safro today' },
  'auth.fullName': { ar: 'الاسم الكامل', en: 'Full Name' },
  'auth.iAm': { ar: 'أنا...', en: 'I am a...' },
  'auth.customer': { ar: 'عميل (أحجز مقاعد)', en: 'Customer (book seats)' },
  'auth.companyAdmin': { ar: 'مدير شركة (إدارة الباصات والرحلات)', en: 'Company Admin (manage buses & trips)' },
  'auth.companyIdLabel': { ar: 'رقم الشركة', en: 'Company ID' },
  'auth.askAdmin': { ar: 'اسأل المدير عن هذا', en: 'Ask your admin for this' },
  'auth.alreadyAccount': { ar: 'عندك حساب؟', en: 'Already have an account?' },
  'auth.signIn': { ar: 'تسجيل الدخول', en: 'Sign in' },
  'auth.demoAccounts': { ar: 'حسابات تجريبية', en: 'Demo accounts' },
  'auth.admin': { ar: 'مدير', en: 'Admin' },
  'auth.superAdmin': { ar: 'سوبر أدمن', en: 'Super Admin' },
  'auth.user': { ar: 'مستخدم', en: 'User' },

  // Common
  'common.loading': { ar: 'جارِ التحميل...', en: 'Loading...' },
  'common.error': { ar: 'خطأ', en: 'Error' },
  'common.success': { ar: 'نجاح', en: 'Success' },
  'common.cancel': { ar: 'إلغاء', en: 'Cancel' },
  'common.save': { ar: 'حفظ', en: 'Save' },
  'common.delete': { ar: 'حذف', en: 'Delete' },
  'common.edit': { ar: 'تعديل', en: 'Edit' },
  'common.confirm': { ar: 'تأكيد', en: 'Confirm' },
  'common.confirmed': { ar: 'مؤكد', en: 'Confirmed' },
  'common.pending': { ar: 'معلق', en: 'Pending' },
  'common.cancelled': { ar: 'ملغى', en: 'Cancelled' },
  'common.guest': { ar: 'زائر', en: 'Guest' },
  'common.currency': { ar: 'ج.م', en: 'EGP' },

  // Stations
  'station.title': { ar: 'المحطات', en: 'Stations' },
  'station.manage': { ar: 'إدارة محطات الباص', en: 'Manage Bus Stations' },
  'station.addStation': { ar: 'إضافة محطة', en: 'Add Station' },
  'station.stationName': { ar: 'اسم المحطة', en: 'Station Name' },
  'station.noStations': { ar: 'لا توجد محطات', en: 'No stations yet' },
  'station.addFirst': { ar: 'أضف أول محطة للباص', en: 'Add your first station' },
  'station.saveStations': { ar: 'حفظ المحطات', en: 'Save Stations' },
  'station.stationsCount': { ar: 'محطة', en: 'stations' },
  'station.stopsAt': { ar: 'محطات التوقف', en: 'Stops at' },
  'station.selectStation': { ar: 'اختر محطة', en: 'Select station' },

  // Round Trip
  'roundtrip.toggle': { ar: 'ذهاب وعودة', en: 'Round Trip' },
  'roundtrip.outbound': { ar: 'ذهاب', en: 'Outbound' },
  'roundtrip.return': { ar: 'عودة', en: 'Return' },
  'roundtrip.returnDate': { ar: 'تاريخ العودة', en: 'Return Date' },
  'roundtrip.selectReturn': { ar: 'اختر رحلة العودة', en: 'Select Return Trip' },
  'roundtrip.noReturnTrips': { ar: 'لا توجد رحلات عودة متاحة', en: 'No return trips available' },
  'roundtrip.outboundTrip': { ar: 'رحلة الذهاب', en: 'Outbound Trip' },
  'roundtrip.returnTrip': { ar: 'رحلة العودة', en: 'Return Trip' },
  'roundtrip.totalBoth': { ar: 'إجمالي الذهاب والعودة', en: 'Total (Both Ways)' },
  'roundtrip.bothLegs': { ar: 'الذهاب والعودة', en: 'Round Trip' },

  // Cancellation Policy
  'cancel.policy': { ar: 'سياسة الإلغاء', en: 'Cancellation Policy' },
  'cancel.confirmTitle': { ar: 'تأكيد الإلغاء', en: 'Confirm Cancellation' },
  'cancel.confirmDesc': { ar: 'سيتم استرداد {amount} لطريقة الدفع الأصلية', en: '{amount} will be refunded to your original payment method' },
  'cancel.refundAmount': { ar: 'مبلغ الاسترداد', en: 'Refund Amount' },
  'cancel.fee': { ar: 'رسوم الإلغاء', en: 'Cancellation Fee' },
  'cancel.reason': { ar: 'سبب الإلغاء', en: 'Reason for cancellation' },
  'cancel.reasonChangedPlans': { ar: 'تغيرت الخطط', en: 'Changed plans' },
  'cancel.reasonFoundAlternative': { ar: 'وجدت بديل', en: 'Found alternative' },
  'cancel.reasonOther': { ar: 'أخرى', en: 'Other' },
  'cancel.freeWindow': { ar: 'إلغاء مجاني', en: 'Free cancellation' },
  'cancel.partialRefund': { ar: 'استرداد جزئي', en: 'Partial refund' },
  'cancel.noRefund': { ar: 'لا يوجد استرداد', en: 'No refund' },
  'cancel.cannotCancel': { ar: 'لا يمكن إلغاء هذا الحجز', en: 'This booking cannot be cancelled' },
  'cancel.alreadyCancelled': { ar: 'تم إلغاء هذا الحجز بالفعل', en: 'This booking is already cancelled' },
  'cancel.alreadyBoarded': { ar: 'لا يمكن الإلغاء بعد الصعود', en: 'Cannot cancel after boarding' },
  'cancel.roundTripWarning': { ar: 'هل تريد إلغاء رحلة العودة أيضاً؟', en: 'Do you want to cancel the return trip as well?' },
  'cancel.adminOverride': { ar: 'تجاوز السياسة (استرداد كامل)', en: 'Override policy (full refund)' },
  'cancel.hoursBefore': { ar: 'قبل المغادرة', en: 'before departure' },
  'cancel.fullRefund': { ar: 'استرداد كامل', en: 'Full refund' },
  'cancel.noRefundAfter': { ar: 'لا استرداد بعد المغادرة', en: 'No refund after departure' },
  'cancel.departureIn': { ar: 'المغادرة خلال', en: 'Departure in' },
  'cancel.refundTo': { ar: 'سيتم الاسترداد لـ', en: 'Refund to' },
  'cancel.cancelledAt': { ar: 'تم الإلغاء في', en: 'Cancelled at' },
  'cancel.reasonLabel': { ar: 'السبب', en: 'Reason' },
  'cancel.refundedAmount': { ar: 'المبلغ المسترد', en: 'Refunded amount' },
  'cancel.refundProcessed': { ar: 'تم صرف المبلغ', en: 'Refund processed' },
  'cancel.refundPending': { ar: 'في انتظار المعالجة', en: 'Pending processing' },
  'cancel.refundPendingDesc': { ar: 'في انتظار موافقة الأدمن', en: 'Awaiting admin approval' },

  // Admin Cancellations
  'admin.cancellations': { ar: 'الإلغاءات', en: 'Cancellations' },
  'admin.cancellationsKpi': { ar: 'بانتظار المعالجة', en: 'Pending cancellations' },

  // Station Page (Customer)
  'stations.pageTitle': { ar: 'المحطات', en: 'Stations' },
  'stations.pageDesc': { ar: 'اختر محطة لعرض الرحلات المتاحة', en: 'Select a station to view available trips' },
  'stations.searchPlaceholder': { ar: 'ابحث عن محطة...', en: 'Search stations...' },
  'stations.filterByCity': { ar: 'تصفية حسب المدينة', en: 'Filter by city' },
  'stations.allCities': { ar: 'كل المدن', en: 'All cities' },
  'stations.tripsFrom': { ar: 'الرحلات من', en: 'Trips from' },
  'stations.noTripsFrom': { ar: 'لا توجد رحلات متاحة من هذه المحطة حالياً', en: 'No trips available from this station currently' },
  'stations.bookNow': { ar: 'احجز الآن', en: 'Book Now' },
  'stations.noStations': { ar: 'لا توجد محطات', en: 'No stations found' },
  'stations.tripsCount': { ar: 'رحلة', en: 'trips' },

  // Station Admin
  'station.edit': { ar: 'تعديل المحطة', en: 'Edit Station' },
  'station.delete': { ar: 'حذف المحطة', en: 'Delete Station' },
  'station.confirmDelete': { ar: 'هل أنت متأكد من حذف هذه المحطة؟', en: 'Are you sure you want to delete this station?' },
  'station.city': { ar: 'المدينة', en: 'City' },
  'station.usedInTrips': { ar: 'مستخدمة في الرحلات', en: 'Used in trips' },
  'station.update': { ar: 'تحديث', en: 'Update' },
  'station.deleteConfirm': { ar: 'هل أنت متأكد؟ هذه المحطة مستخدمة في {count} رحلة', en: 'Are you sure? This station is used in {count} trips' },
  'station.cannotDelete': { ar: 'لا يمكن حذف المحطة لأنها مستخدمة في رحلات', en: 'Cannot delete station as it is used in trips' },

  // FAQ
  'faq.title': { ar: 'الأسئلة الشائعة', en: 'Frequently Asked Questions' },
  'faq.subtitle': { ar: 'إجابات لأكثر الأسئلة شيوعاً', en: 'Answers to common questions' },
  'faq.addQuestion': { ar: 'إضافة سؤال', en: 'Add Question' },
  'faq.editQuestion': { ar: 'تعديل السؤال', en: 'Edit Question' },
  'faq.questionAr': { ar: 'السؤال (عربي)', en: 'Question (Arabic)' },
  'faq.questionEn': { ar: 'السؤال (إنجليزي)', en: 'Question (English)' },
  'faq.answerAr': { ar: 'الإجابة (عربي)', en: 'Answer (Arabic)' },
  'faq.answerEn': { ar: 'الإجابة (إنجليزي)', en: 'Answer (English)' },
  'faq.noFaqs': { ar: 'لا توجد أسئلة', en: 'No FAQs yet' },
  'faq.addFirst': { ar: 'أضف أول سؤال', en: 'Add your first FAQ' },
  'faq.moveUp': { ar: 'تحريك لأعلى', en: 'Move Up' },
  'faq.moveDown': { ar: 'تحريك لأسفل', en: 'Move Down' },
  'faq.active': { ar: 'مفعل', en: 'Active' },
  'faq.inactive': { ar: 'معطل', en: 'Inactive' },
  'faq.seedSuccess': { ar: 'تم إضافة الأسئلة الافتراضية', en: 'Default FAQs added' },
  'faq.alreadySeeded': { ar: 'الأسئلة الافتراضية موجودة بالفعل', en: 'Default FAQs already exist' },
  'faq.manage': { ar: 'إدارة الأسئلة الشائعة', en: 'Manage FAQs' },
  'faq.seedDefaults': { ar: 'إضافة الأسئلة الافتراضية', en: 'Seed Default Questions' },
  'faq.confirmDelete': { ar: 'هل أنت متأكد من حذف هذا السؤال؟', en: 'Are you sure you want to delete this question?' },
  'faq.searchPlaceholder': { ar: 'ابحث في الأسئلة...', en: 'Search questions...' },
  'faq.showAll': { ar: 'عرض الكل', en: 'Show all' },
  'faq.showActive': { ar: 'المفعلة فقط', en: 'Active only' },

  // Payment
  'payment.pending': { ar: 'في انتظار تأكيد الدفع', en: 'Awaiting Payment Confirmation' },
  'payment.confirmed': { ar: 'تم تأكيد الدفع', en: 'Payment Confirmed' },
  'payment.confirmBtn': { ar: 'تأكيد الدفع', en: 'Confirm Payment' },
  'payment.confirmTitle': { ar: 'تأكيد استلام الدفع', en: 'Confirm Payment Received' },
  'payment.pendingDesc': { ar: 'سيتم تأكيد الحجز بعد استلام الأدمن للدفع', en: 'Booking will be confirmed after admin receives payment' },
  'payment.cash': { ar: 'الدفع نقداً عند المحطة أو تحويل بنكي', en: 'Cash at station or bank transfer' },

  'company.dashboard': { ar: 'لوحة التحكم', en: 'Dashboard' },
  'company.welcome': { ar: 'مرحباً', en: 'Welcome' },
  'company.walletBalance': { ar: 'رصيد المحفظة', en: 'Wallet Balance' },
  'company.creditLimit': { ar: 'حد الكريدت', en: 'Credit Limit' },
  'company.availableCredit': { ar: 'الكريدت المتاح', en: 'Available Credit' },
  'company.outstanding': { ar: 'المبلغ المستحق', en: 'Outstanding Balance' },
  'company.totalBookings': { ar: 'إجمالي الحجوزات', en: 'Total Bookings' },
  'company.totalSpent': { ar: 'إجمالي المصروفات', en: 'Total Spent' },
  'company.newBooking': { ar: 'حجز جديد', en: 'New Booking' },
  'company.deposit': { ar: 'شحن رصيد', en: 'Deposit' },
  'company.viewInvoices': { ar: 'عرض الفواتير', en: 'View Invoices' },
  'company.recentBookings': { ar: 'آخر الحجوزات', en: 'Recent Bookings' },
  'company.bookings': { ar: 'الحجوزات', en: 'Bookings' },
  'company.customers': { ar: 'العملاء', en: 'Customers' },
  'company.credit': { ar: 'الكريدت', en: 'Credit' },
  'company.invoices': { ar: 'الفواتير', en: 'Invoices' },
  'company.customerName': { ar: 'اسم العميل', en: 'Customer Name' },
  'company.customerEmail': { ar: 'البريد الإلكتروني', en: 'Email' },
  'company.customerPhone': { ar: 'رقم الهاتف', en: 'Phone Number' },
  'company.customerNotes': { ar: 'ملاحظات', en: 'Notes' },
  'company.addCustomer': { ar: 'إضافة عميل', en: 'Add Customer' },
  'company.editCustomer': { ar: 'تعديل العميل', en: 'Edit Customer' },
  'company.deleteCustomer': { ar: 'حذف العميل', en: 'Delete Customer' },
  'company.bookingType': { ar: 'نوع الحجز', en: 'Booking Type' },
  'company.forClient': { ar: 'لعميل', en: 'For Client' },
  'company.forEmployee': { ar: 'لموظف', en: 'For Employee' },
  'company.selectCustomer': { ar: 'اختر عميل', en: 'Select Customer' },
  'company.newCustomer': { ar: 'عميل جديد', en: 'New Customer' },
  'company.passengerName': { ar: 'اسم المسافر', en: 'Passenger Name' },
  'company.passengerPhone': { ar: 'هاتف المسافر', en: 'Passenger Phone' },
  'company.paidFromWallet': { ar: 'مدفوع من المحفظة', en: 'Paid from Wallet' },
  'company.paidOnCredit': { ar: 'مدفوع بالكريدت', en: 'Paid on Credit' },
  'company.wallet': { ar: 'المحفظة', en: 'Wallet' },
  'company.depositAmount': { ar: 'مبلغ الشحن', en: 'Deposit Amount' },
  'company.transactionHistory': { ar: 'سجل المعاملات', en: 'Transaction History' },
  'company.depositType': { ar: 'شحن', en: 'Deposit' },
  'company.chargeType': { ar: 'خصم حجز', en: 'Booking Charge' },
  'company.refundType': { ar: 'استرداد', en: 'Refund' },
  'company.adjustmentType': { ar: 'تعديل', en: 'Adjustment' },
  'company.invoicePeriod': { ar: 'فترة الفاتورة', en: 'Invoice Period' },
  'company.invoiceTotal': { ar: 'إجمالي الفاتورة', en: 'Invoice Total' },
  'company.invoicePaid': { ar: 'المبلغ المدفوع', en: 'Paid Amount' },
  'company.invoiceRemaining': { ar: 'المتبقي', en: 'Remaining' },
  'company.dueDate': { ar: 'تاريخ الاستحقاق', en: 'Due Date' },
  'company.invoiceStatus': { ar: 'حالة الفاتورة', en: 'Invoice Status' },
  'company.invoicePending': { ar: 'قيد الانتظار', en: 'Pending' },
  'company.invoicePartial': { ar: 'مدفوعة جزئياً', en: 'Partially Paid' },
  'company.invoicePaidStatus': { ar: 'مدفوعة', en: 'Paid' },
  'company.invoiceOverdue': { ar: 'متأخرة', en: 'Overdue' },
  'company.payInvoice': { ar: 'دفع الفاتورة', en: 'Pay Invoice' },
  'company.insufficientWallet': { ar: 'رصيد المحفظة غير كافي', en: 'Insufficient wallet balance' },
  'company.creditLimitExceeded': { ar: 'تم تجاوز حد الكريدت', en: 'Credit limit exceeded' },
  'company.companyInactive': { ar: 'حساب الشركة غير مفعّل', en: 'Company account is inactive' },
  'company.bookingSuccess': { ar: 'تم الحجز بنجاح', en: 'Booking successful' },
  'company.bookingFailed': { ar: 'فشل الحجز', en: 'Booking failed' },
  'company.confirmDeposit': { ar: 'تأكيد الشحن', en: 'Confirm Deposit' },
  'company.confirmDepositDesc': { ar: 'هل تريد شحن {amount} في محفظتك؟', en: 'Do you want to deposit {amount} to your wallet?' },
  'company.noCustomers': { ar: 'لا يوجد عملاء بعد', en: 'No customers yet' },
  'company.noBookings': { ar: 'لا توجد حجوزات', en: 'No bookings found' },
  'company.noInvoices': { ar: 'لا توجد فواتير', en: 'No invoices found' },
  'company.noTransactions': { ar: 'لا توجد معاملات', en: 'No transactions found' },
  'company.quickActions': { ar: 'إجراءات سريعة', en: 'Quick Actions' },
  'company.paymentMode': { ar: 'وضع الدفع', en: 'Payment Mode' },
  'company.creditMode': { ar: 'كريدت (فاتورة شهرية)', en: 'Credit (Monthly Invoice)' },
  'company.prepaidMode': { ar: 'مسبق الدفع (محفظة)', en: 'Prepaid (Wallet)' },
  'company.bothMode': { ar: 'كلاهما (محفظة + كريدت)', en: 'Both (Wallet + Credit)' },
  'company.billingCycle': { ar: 'دورة الفوترة', en: 'Billing Cycle' },
  'company.monthly': { ar: 'شهري', en: 'Monthly' },
  'company.weekly': { ar: 'أسبوعي', en: 'Weekly' },
  'company.isActive': { ar: 'مفعّل', en: 'Active' },
  'company.isInactive': { ar: 'غير مفعّل', en: 'Inactive' },
  'company.activate': { ar: 'تفعيل', en: 'Activate' },
  'company.deactivate': { ar: 'إيقاف', en: 'Deactivate' },
  'company.creditReport': { ar: 'تقرير الكريدت', en: 'Credit Report' },
  'company.usagePercent': { ar: 'نسبة الاستخدام', en: 'Usage %' },
  'company.editCompany': { ar: 'تعديل الشركة', en: 'Edit Company' },
  'company.manageCompanies': { ar: 'إدارة الشركات', en: 'Manage Companies' },
  'company.tripRequests': { ar: 'طلب رحلة', en: 'Trip Request' },
  'admin.tripRequests': { ar: 'طلبات الرحلات', en: 'Trip Requests' },
  'tripRequest.title': { ar: 'طلب رحلة مخصوصة', en: 'Custom Trip Request' },
  'tripRequest.newRequest': { ar: 'طلب رحلة جديدة', en: 'New Trip Request' },
  'tripRequest.from': { ar: 'من', en: 'From' },
  'tripRequest.to': { ar: 'إلى', en: 'To' },
  'tripRequest.date': { ar: 'التاريخ', en: 'Date' },
  'tripRequest.passengerCount': { ar: 'عدد الأفراد', en: 'Passenger Count' },
  'tripRequest.notes': { ar: 'ملاحظات', en: 'Notes' },
  'tripRequest.submit': { ar: 'إرسال الطلب', en: 'Submit Request' },
  'tripRequest.pending': { ar: 'قيد المراجعة', en: 'Pending' },
  'tripRequest.approved': { ar: 'تمت الموافقة', en: 'Approved' },
  'tripRequest.rejected': { ar: 'مرفوض', en: 'Rejected' },
  'tripRequest.reason': { ar: 'سبب الرفض', en: 'Rejection Reason' },
  'tripRequest.approve': { ar: 'موافقة', en: 'Approve' },
  'tripRequest.reject': { ar: 'رفض', en: 'Reject' },
  'tripRequest.adminNotes': { ar: 'ملاحظات الإدارة', en: 'Admin Notes' },
  'tripRequest.noRequests': { ar: 'لا توجد طلبات', en: 'No requests yet' },
  'tripRequest.status': { ar: 'الحالة', en: 'Status' },
  'tripRequest.createdAt': { ar: 'تاريخ الطلب', en: 'Request Date' },
  'tripRequest.success': { ar: 'تم إرسال الطلب بنجاح', en: 'Request submitted successfully' },
  'tripRequest.approvedMsg': { ar: 'تمت الموافقة على الطلب', en: 'Request approved' },
  'tripRequest.rejectedMsg': { ar: 'تم رفض الطلب', en: 'Request rejected' },
  'admin.depositRequests': { ar: 'طلبات الشحن', en: 'Deposit Requests' },
  'depositRequest.title': { ar: 'طلب شحن رصيد', en: 'Wallet Deposit Request' },
  'depositRequest.newRequest': { ar: 'طلب شحن جديد', en: 'New Deposit Request' },
  'depositRequest.amount': { ar: 'المبلغ', en: 'Amount' },
  'depositRequest.submit': { ar: 'إرسال الطلب', en: 'Submit Request' },
  'depositRequest.pending': { ar: 'قيد المراجعة', en: 'Pending' },
  'depositRequest.approved': { ar: 'تمت الموافقة', en: 'Approved' },
  'depositRequest.rejected': { ar: 'مرفوض', en: 'Rejected' },
  'depositRequest.reason': { ar: 'سبب الرفض', en: 'Rejection Reason' },
  'depositRequest.approve': { ar: 'موافقة', en: 'Approve' },
  'depositRequest.reject': { ar: 'رفض', en: 'Reject' },
  'depositRequest.adminNotes': { ar: 'ملاحظات الإدارة', en: 'Admin Notes' },
  'depositRequest.noRequests': { ar: 'لا توجد طلبات شحن', en: 'No deposit requests' },
  'depositRequest.success': { ar: 'تم إرسال طلب الشحن بنجاح', en: 'Deposit request submitted successfully' },
  'depositRequest.approvedMsg': { ar: 'تمت الموافقة على طلب الشحن', en: 'Deposit request approved' },
  'depositRequest.rejectedMsg': { ar: 'تم رفض طلب الشحن', en: 'Deposit request rejected' },
  'depositRequest.company': { ar: 'الشركة', en: 'Company' },
  'depositRequest.date': { ar: 'تاريخ الطلب', en: 'Request Date' },
  'depositRequest.status': { ar: 'الحالة', en: 'Status' },
  'depositRequest.confirmDeposit': { ar: 'تأكيد طلب الشحن', en: 'Confirm Deposit Request' },
  'admin.pendingCompanies': { ar: 'شركات معلقة', en: 'Pending Companies' },
  'auth.registerCompany': { ar: 'تسجيل شركتك', en: 'Register Your Company' },
  'auth.orCompany': { ar: 'أو سجل شركتك', en: 'or register your company' },

  // V2 design system (single source of truth for redesigned pages)
  'v2.brand': { ar: 'سفرو', en: 'Safro' },
  'v2.explore': { ar: 'استكشف', en: 'Explore' },
  'v2.trips': { ar: 'الرحلات', en: 'Trips' },
  'v2.destinations': { ar: 'الوجهات', en: 'Destinations' },
  'v2.forBusiness': { ar: 'للشركات', en: 'For Businesses' },
  'v2.login': { ar: 'تسجيل الدخول', en: 'Login' },
  'v2.bookTrip': { ar: 'احجز رحلة', en: 'Book a trip' },
  'v2.myBookings': { ar: 'حجوزاتي', en: 'My Bookings' },
  'v2.account': { ar: 'حسابي', en: 'Account' },
  'v2.heroEyebrow': { ar: 'سفر للجميع', en: 'TRAVEL FOR EVERYONE' },
  'v2.heroTitleA': { ar: 'سافر أبعد', en: 'Go further' },
  'v2.heroTitleB': { ar: 'معًا.', en: 'together.' },
  'v2.heroSubtitle': { ar: 'رحلات باص مريحة داخل مصر — لك، أو لمجموعتك، أو لشركتك.', en: 'Comfortable bus travel across Egypt — for yourself, your group, or your business.' },
  'v2.individual': { ar: 'للأفراد', en: 'Individual' },
  'v2.business': { ar: 'للشركات (B2B)', en: 'Business (B2B)' },
  'v2.from': { ar: 'من', en: 'From' },
  'v2.to': { ar: 'إلى', en: 'To' },
  'v2.date': { ar: 'التاريخ', en: 'Date' },
  'v2.passengers': { ar: 'المسافرون', en: 'Passengers' },
  'v2.pickup': { ar: 'مكان التحرك', en: 'Pickup location' },
  'v2.destination': { ar: 'الوجهة', en: 'Destination' },
  'v2.travelDate': { ar: 'تاريخ السفر', en: 'Travel date' },
  'v2.tripType': { ar: 'نوع الرحلة', en: 'Trip type' },
  'v2.charter': { ar: 'احجز باصًا كاملًا', en: 'Book an entire bus' },
  'v2.oneWay': { ar: 'ذهاب فقط', en: 'One way' },
  'v2.roundTrip': { ar: 'ذهاب وعودة', en: 'Round trip' },
  'v2.searchTrips': { ar: 'ابحث عن الرحلات', en: 'Search trips' },
  'v2.requestBus': { ar: 'اطلب باص', en: 'Request a bus' },
  'v2.fromPh': { ar: 'مثال: القاهرة', en: 'e.g. Cairo' },
  'v2.toPh': { ar: 'مثال: المنصورة', en: 'e.g. Mansoura' },
  'v2.trustRoutes': { ar: '+120 مسار', en: '120+ routes' },
  'v2.trustRoutesSub': { ar: 'داخل مصر', en: 'Across Egypt' },
  'v2.trustStations': { ar: '+40 محطة', en: '40+ stations' },
  'v2.trustStationsSub': { ar: 'في المدن الكبرى', en: 'In major cities' },
  'v2.trustSecure': { ar: 'حجز آمن', en: 'Secure booking' },
  'v2.trustSecureSub': { ar: 'سلامتك أولًا', en: 'Your safety matters' },
  'v2.trustGreen': { ar: 'سفر صديق للبيئة', en: 'Greener travel' },
  'v2.trustGreenSub': { ar: 'بصمة كربونية أقل', en: 'Lower carbon footprint' },
  'v2.popularTitle': { ar: 'الوجهات الأكثر شعبية', en: 'Popular destinations' },
  'v2.popularSub': { ar: 'اكتشف أماكن مذهلة، وسافر إليها براحة.', en: 'Discover amazing places, and get there comfortably.' },
  'v2.exploreAll': { ar: 'استكشف كل الوجهات', en: 'Explore all destinations' },
  'v2.fromPrice': { ar: 'ابتداءً من', en: 'From' },
  'v2.howEyebrow': { ar: 'كيف يعمل سفرو', en: 'HOW IT WORKS' },
  'v2.howTitle': { ar: 'خطوات بسيطة. حجز سهل.', en: 'Simple steps. Easy booking.' },
  'v2.howSub': { ar: 'اختر مسارك، وقارن الخيارات، واحجز مقعدك، واستلم تذكرتك في دقائق.', en: 'Find your route, compare options, choose your seat, and get your ticket in minutes.' },
  'v2.howCta': { ar: 'احجز رحلة', en: 'Book a trip' },
  'v2.how1t': { ar: 'ابحث', en: 'Search' },
  'v2.how1d': { ar: 'أدخل مدينتك وتاريخك وعدد المسافرين.', en: 'Enter your cities, date and passengers.' },
  'v2.how2t': { ar: 'قارن', en: 'Compare' },
  'v2.how2d': { ar: 'شاهد الباصات والأسعار والخدمات.', en: 'See available buses, prices and amenities.' },
  'v2.how3t': { ar: 'اختر مقعدك', en: 'Choose seat' },
  'v2.how3d': { ar: 'اختر الباص والمقعد المناسب لك.', en: 'Pick your preferred seat in real time.' },
  'v2.how4t': { ar: 'ادفع واستلم', en: 'Pay & get ticket' },
  'v2.how4d': { ar: 'دفع آمن وتذكرة إلكترونية فورية.', en: 'Secure payment and instant e-ticket.' },
  'v2.featTitle': { ar: 'رحلات مميزة', en: 'Featured trips' },
  'v2.featSub': { ar: 'باصات مريحة. شركات موثوقة. مواعيد مرنة.', en: 'Comfortable buses. Trusted operators. Flexible schedules.' },
  'v2.viewAll': { ar: 'عرض كل الرحلات', en: 'View all trips' },
  'v2.direct': { ar: 'مباشر', en: 'Direct' },
  'v2.perPassenger': { ar: '/ للمسافر', en: '/ passenger' },
  'v2.selectTrip': { ar: 'اختر الرحلة', en: 'Select trip' },
  'v2.b2bEyebrow': { ar: 'حلول الشركات', en: 'B2B SOLUTIONS' },
  'v2.b2bTitle': { ar: 'باصات خاصة. بسّط سفر مجموعتك.', en: 'Charter buses. Simplify your group travel.' },
  'v2.b2bSub': { ar: 'للشركات والمدارس والمؤسسات — احجز باصات كاملة ونظّم رحلاتك بدعم مخصص، كل ذلك من مكان واحد.', en: 'For companies, schools, and organizations — book full buses, manage trips, and get dedicated support, all in one place.' },
  'v2.b2bCta': { ar: 'اكتشف حلول الشركات', en: 'Explore B2B Solutions' },
  'v2.footerTag': { ar: 'رحلات أكثر. إمكانيات أكبر.', en: 'More journeys. Bigger possibilities.' },
  'v2.quickLinks': { ar: 'روابط سريعة', en: 'Quick links' },
  'v2.support': { ar: 'الدعم', en: 'Support' },
  'v2.stayLoop': { ar: 'ابق على اطلاع', en: 'Stay in the loop' },
  'v2.staySub': { ar: 'أحدث المسارات والعروض ونصائح السفر.', en: 'Get the latest routes, offers and travel tips.' },
  'v2.emailPh': { ar: 'بريدك الإلكتروني', en: 'Your email address' },
  'v2.rights': { ar: '© 2026 سفرو. جميع الحقوق محفوظة.', en: '© 2026 Safro. All rights reserved.' },
  'v2.searchTitle': { ar: 'ابحث عن رحلتك', en: 'Find your trip' },
  'v2.searchSub': { ar: 'اختر محطتي المغادرة والوصول والتاريخ لعرض الرحلات المتاحة.', en: 'Pick origin, destination and date to see available trips.' },
  'v2.allStations': { ar: 'كل المحطات', en: 'All stations' },
  'v2.anyDate': { ar: 'أي تاريخ', en: 'Any date' },
  'v2.resultsTitle': { ar: 'الرحلات المتاحة', en: 'Available trips' },
  'v2.noTrips': { ar: 'لا توجد رحلات مطابقة', en: 'No matching trips' },
  'v2.noTripsDesc': { ar: 'جرّب تغيير المحطات أو التاريخ ثم ابحث مرة أخرى.', en: 'Try different stations or another date.' },
  'v2.clearFilters': { ar: 'مسح الفلاتر', en: 'Clear filters' },
  'v2.loadingTrips': { ar: 'جاري تحميل الرحلات...', en: 'Loading trips...' },
  'v2.loadFailed': { ar: 'تعذّر تحميل الرحلات', en: 'Could not load trips' },
  'v2.loadFailedDesc': { ar: 'حدث خطأ أثناء الاتصال بالخادم. حاول مرة أخرى.', en: 'Something went wrong reaching the server. Try again.' },
  'v2.retry': { ar: 'حاول مرة أخرى', en: 'Try again' },
  'v2.seatsLeft': { ar: 'مقاعد متاحة', en: 'seats left' },
  'v2.soldOut': { ar: 'مكتمل العدد', en: 'Sold out' },
  'v2.stops': { ar: 'محطات', en: 'stops' },
  'v2.loginToSearch': { ar: 'سجّل الدخول للبحث', en: 'Log in to search' },
  'v2.loginToSearchDesc': { ar: 'سجّل الدخول لعرض الرحلات المتاحة والحجز.', en: 'Log in to see available trips and book.' },
  'auth.registeredOk': { ar: 'تم إنشاء حسابك بنجاح. سجّل الدخول للمتابعة.', en: 'Account created successfully. Sign in to continue.' },
  'v2.stepDetails': { ar: 'التفاصيل', en: 'Details' },
  'v2.stepSeats': { ar: 'المقاعد', en: 'Seats' },
  'v2.stepPassengers': { ar: 'المسافرون', en: 'Passengers' },
  'v2.stepReview': { ar: 'المراجعة', en: 'Review' },
  'v2.pickStops': { ar: 'اختر محطتي الصعود والنزول', en: 'Pick boarding and alighting stops' },
  'v2.boardFrom': { ar: 'الصعود من', en: 'Board at' },
  'v2.alightAt': { ar: 'النزول في', en: 'Alight at' },
  'v2.confirmStops': { ar: 'تأكيد المحطات', en: 'Confirm stops' },
  'v2.operator': { ar: 'الشركة المشغلة', en: 'Operator' },
  'v2.timeline': { ar: 'خط الرحلة', en: 'Route timeline' },
  'v2.continue': { ar: 'متابعة', en: 'Continue' },
  'v2.back': { ar: 'رجوع', en: 'Back' },
  'v2.passengerNamePh': { ar: 'اسم المسافر', en: 'Passenger name' },
  'v2.passengerPhonePh': { ar: 'رقم الهاتف', en: 'Phone number' },
  'v2.hotelPh': { ar: 'الفندق (اختياري)', en: 'Hotel (optional)' },
  'v2.orderSummary': { ar: 'ملخص الحجز', en: 'Booking summary' },
  'v2.total': { ar: 'الإجمالي', en: 'Total' },
  'v2.confirmBooking': { ar: 'تأكيد الحجز', en: 'Confirm booking' },
  'v2.bookingNow': { ar: 'جاري تنفيذ الحجز...', en: 'Booking...' },
  'v2.bookedOk': { ar: 'تم الحجز بنجاح', en: 'Booking confirmed' },
  'v2.bookedPending': { ar: 'حجزك قيد الانتظار. ادفع في المحطة لتأكيد مقعدك.', en: 'Your booking is pending. Pay at the station to confirm your seat.' },
  'v2.viewBookings': { ar: 'عرض حجوزاتي', en: 'View my bookings' },
  'v2.bookAnother': { ar: 'حجز رحلة أخرى', en: 'Book another trip' },
  'v2.returnLeg': { ar: 'رحلة العودة', en: 'Return leg' },
  'v2.outboundLeg': { ar: 'رحلة الذهاب', en: 'Outbound leg' },
  'v2.pickSeatsFirst': { ar: 'اختر مقعدًا أولًا للمتابعة', en: 'Select a seat first to continue' },
  'v2.tripNotFound': { ar: 'الرحلة غير موجودة', en: 'Trip not found' },
  'v2.tabUpcoming': { ar: 'القادمة', en: 'Upcoming' },
  'v2.tabPending': { ar: 'المعلقة', en: 'Pending' },
  'v2.tabPast': { ar: 'السابقة', en: 'Past' },
  'v2.tabCancelled': { ar: 'الملغاة', en: 'Cancelled' },
  'v2.cancelBooking': { ar: 'إلغاء الحجز', en: 'Cancel booking' },
  'v2.cancelReason': { ar: 'سبب الإلغاء (اختياري)', en: 'Cancellation reason (optional)' },
  'v2.refundPreview': { ar: 'المبلغ المسترد', en: 'Refund amount' },
  'v2.cancelFee': { ar: 'رسوم الإلغاء', en: 'Cancellation fee' },
  'v2.keepBooking': { ar: 'الاحتفاظ بالحجز', en: 'Keep booking' },
  'v2.copied': { ar: 'تم النسخ', en: 'Copied' },
  'v2.printTicket': { ar: 'طباعة التذكرة', en: 'Print ticket' },
  'v2.viewTicket': { ar: 'عرض التذكرة', en: 'View ticket' },
  'v2.bookingDetails': { ar: 'تفاصيل الحجز', en: 'Booking details' },
  'v2.profileTitle': { ar: 'حسابي', en: 'My account' },
  'v2.saveChanges': { ar: 'حفظ التغييرات', en: 'Save changes' },
  'v2.savedOk': { ar: 'تم الحفظ بنجاح', en: 'Saved successfully' },
  'v2.changePassword': { ar: 'تغيير كلمة المرور', en: 'Change password' },
  'v2.currentPw': { ar: 'كلمة المرور الحالية', en: 'Current password' },
  'v2.newPw': { ar: 'كلمة المرور الجديدة', en: 'New password' },
  'v2.confirmPw': { ar: 'تأكيد كلمة المرور', en: 'Confirm password' },
  'v2.browseTrips': { ar: 'تصفح الرحلات', en: 'Browse trips' },
  'v2.noBookingsYet': { ar: 'لا توجد حجوزات بعد', en: 'No bookings yet' },
  'v2.noBookingsDesc': { ar: 'احجز رحلتك الأولى داخل مصر اليوم.', en: 'Book your first trip across Egypt today.' },
}

export const useLangStore = create<LangState>()(
  persist(
    (set, get) => ({
      lang: 'ar',
      setLang: (lang) => set({ lang }),
      t: (key) => translations[key]?.[get().lang] || key,
    }),
    { name: 'crushcar-lang' }
  )
)